/*
 * Copyright (c) 2025 NetEase, Inc.
 * All rights reserved.
 */


#ifndef RS_XKIT_BASE_H
#define RS_XKIT_BASE_H

// This file is automatically generated. Do not edit it manually.

/**
 * 通用失败 code
 */
#define XKIT_BASE_ERROR_FAILURE -1

/**
 * 成功 code
 */
#define XKIT_BASE_ERROR_SUCCESS 0

/**
 * 网络异常
 */
#define XKIT_BASE_ERROR_NETWORK_UNAVAILABLE 100003

#define XKIT_BASE_LOG_LEVEL_VERBOSE 0

#define XKIT_BASE_LOG_LEVEL_DEBUG 1

#define XKIT_BASE_LOG_LEVEL_INFO 2

#define XKIT_BASE_LOG_LEVEL_WARN 3

#define XKIT_BASE_LOG_LEVEL_ERROR 4

#define XKIT_BASE_LOG_TYPE_NORMAL 0

#define XKIT_BASE_LOG_TYPE_API 1

#define XKIT_BASE_EVENT_PRIORITY_LOW 0

#define XKIT_BASE_EVENT_PRIORITY_NORMAL 1

#define XKIT_BASE_EVENT_PRIORITY_HIGH 2

typedef struct xkit_base_action_event_t xkit_base_action_event_t;

typedef struct xkit_base_api_event_t xkit_base_api_event_t;

typedef struct xkit_base_interval_event_t xkit_base_interval_event_t;

typedef struct xkit_base_interval_step_t xkit_base_interval_step_t;

typedef struct xkit_base_page_event_t xkit_base_page_event_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void xkit_base_free_c_string(const char *ptr);

bool xkit_base_high_available_init(const char *config);

const char *xkit_base_high_available_get_available_domain_info(const char *app_key);

/**
 * Initialize the XKit logging system
 */
int xkit_base_log_init(int level, const char *path, const char *name_prefix);

/**
 * Check if the logger is initialized
 */
int xkit_base_log_is_initialized(void);

/**
 * Log a verbose/trace message
 */
void xkit_base_log_verbose(const char *tag,
                           int log_type,
                           const char *module_name,
                           int tid,
                           int line,
                           const char *log_message);

/**
 * Log a debug message
 */
void xkit_base_log_debug(const char *tag,
                         int log_type,
                         const char *module_name,
                         int tid,
                         int line,
                         const char *log_message);

/**
 * Log an info message
 */
void xkit_base_log_info(const char *tag,
                        int log_type,
                        const char *module_name,
                        int tid,
                        int line,
                        const char *log_message);

/**
 * Log a warning message
 */
void xkit_base_log_warn(const char *tag,
                        int log_type,
                        const char *module_name,
                        int tid,
                        int line,
                        const char *log_message);

/**
 * Log an error message
 */
void xkit_base_log_error(const char *tag,
                         int log_type,
                         const char *module_name,
                         int tid,
                         int line,
                         const char *log_message);

bool xkit_base_reporter_register_module(const char *module_name,
                                        const char *module_version,
                                        const char *module_app_key,
                                        const char *framework,
                                        const char *channel,
                                        bool report);

bool xkit_base_reporter_report_event(const char *module_name,
                                     const char *user_id,
                                     const char *event_id,
                                     int32_t priority,
                                     const char *data_json);

bool xkit_base_reporter_report_event_with_module_info(const char *module_name,
                                                      const char *module_version,
                                                      const char *module_app_key,
                                                      const char *framework,
                                                      const char *channel,
                                                      const char *user_id,
                                                      const char *event_id,
                                                      int32_t priority,
                                                      const char *data_json);

void xkit_base_reporter_enable_debug_log(bool enabled);

void xkit_base_reporter_set_user_id(const char *user_id);

bool xkit_base_reporter_set_common_properties(const char *properties);

struct xkit_base_api_event_t *xkit_base_api_event_new(const char *method_name);

bool xkit_base_api_event_set_user_id(struct xkit_base_api_event_t *api_event, const char *user_id);

bool xkit_base_api_event_set_request_id(struct xkit_base_api_event_t *api_event,
                                        const char *request_id);

bool xkit_base_api_event_set_extension(struct xkit_base_api_event_t *api_event,
                                       const char *extension);

bool xkit_base_api_event_set_id1(struct xkit_base_api_event_t *api_event, const char *id1);

bool xkit_base_api_event_set_id2(struct xkit_base_api_event_t *api_event, const char *id2);

bool xkit_base_api_event_add_param(struct xkit_base_api_event_t *api_event,
                                   const char *param_key,
                                   const char *param_value);

bool xkit_base_api_event_set_result(struct xkit_base_api_event_t *api_event,
                                    int32_t code,
                                    const char *message,
                                    const char *request_id);

bool xkit_base_api_event_report(struct xkit_base_api_event_t *api_event,
                                const char *module_name,
                                const char *user_id);

void xkit_base_api_event_free(struct xkit_base_api_event_t *api_event);

struct xkit_base_page_event_t *xkit_base_page_event_new_open(const char *page_name,
                                                             const char *pre_page_name);

struct xkit_base_page_event_t *xkit_base_page_event_new_close(const char *page_name,
                                                              const char *pre_page_name);

bool xkit_base_page_event_turn_close(struct xkit_base_page_event_t *page_event);

bool xkit_base_page_event_set_end_time(struct xkit_base_page_event_t *page_event,
                                       uint64_t end_time);

bool xkit_base_page_event_set_id1(struct xkit_base_page_event_t *page_event, const char *id1);

bool xkit_base_page_event_set_id2(struct xkit_base_page_event_t *page_event, const char *id2);

bool xkit_base_page_event_add_param(struct xkit_base_page_event_t *page_event,
                                    const char *param_key,
                                    const char *param_value);

bool xkit_base_page_event_report(struct xkit_base_page_event_t *page_event,
                                 const char *module_name,
                                 const char *user_id);

void xkit_base_page_event_free(struct xkit_base_page_event_t *page_event);

struct xkit_base_action_event_t *xkit_base_action_event_new_click(const char *action_name,
                                                                  const char *action_title);

struct xkit_base_action_event_t *xkit_base_action_event_new_input(const char *action_name,
                                                                  const char *action_title);

struct xkit_base_action_event_t *xkit_base_action_event_new_custom(const char *action_name,
                                                                   const char *action_title);

bool xkit_base_action_event_set_id1(struct xkit_base_action_event_t *action_event, const char *id1);

bool xkit_base_action_event_set_id2(struct xkit_base_action_event_t *action_event, const char *id2);

bool xkit_base_action_event_add_param(struct xkit_base_action_event_t *action_event,
                                      const char *param_key,
                                      const char *param_value);

bool xkit_base_action_event_report(struct xkit_base_action_event_t *action_event,
                                   const char *module_name,
                                   const char *user_id);

void xkit_base_action_event_free(struct xkit_base_action_event_t *action_event);

struct xkit_base_interval_event_t *xkit_base_interval_event_new(const char *event_id,
                                                                int32_t priority);

struct xkit_base_interval_step_t *xkit_base_interval_event_begin_step(struct xkit_base_interval_event_t *interval_event,
                                                                      const char *step_name);

bool xkit_base_interval_event_set_result(struct xkit_base_interval_event_t *interval_event,
                                         int32_t code,
                                         const char *message,
                                         const char *request_id,
                                         uint64_t server_cost);

bool xkit_base_interval_event_set_step_result(struct xkit_base_interval_event_t *interval_event,
                                              const char *step_name,
                                              int32_t code,
                                              const char *message,
                                              const char *request_id,
                                              uint64_t server_cost);

bool xkit_base_interval_event_add_param(struct xkit_base_interval_event_t *interval_event,
                                        const char *param_key,
                                        const char *param_value);

bool xkit_base_interval_event_report(struct xkit_base_interval_event_t *interval_event,
                                     const char *module_name,
                                     const char *user_id);

void xkit_base_interval_event_free(struct xkit_base_interval_event_t *interval_event);

bool xkit_base_interval_step_set_result(struct xkit_base_interval_step_t *interval_step,
                                        int32_t code,
                                        const char *message,
                                        const char *request_id,
                                        uint64_t server_cost);

bool xkit_base_interval_step_add_param(struct xkit_base_interval_step_t *interval_step,
                                       const char *param_key,
                                       const char *param_value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RS_XKIT_BASE_H */
