// Autogenerated from Pigeon (v9.2.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, FLTCallInitRtcMode) {
  FLTCallInitRtcModeGlobal = 0,
  FLTCallInitRtcModeInNeed = 1,
  FLTCallInitRtcModeInNeedDelayToAccept = 2,
};

typedef NS_ENUM(NSUInteger, FLTCallType) {
  FLTCallTypeNone = 0,
  FLTCallTypeAudio = 1,
  FLTCallTypeVideo = 2,
};

typedef NS_ENUM(NSUInteger, FLTCallEngineStatus) {
  FLTCallEngineStatusIdle = 0,
  FLTCallEngineStatusCalling = 1,
  FLTCallEngineStatusCalled = 2,
  FLTCallEngineStatusInCall = 3,
};

typedef NS_ENUM(NSUInteger, FLTCallSwitchState) {
  FLTCallSwitchStateInvite = 0,
  FLTCallSwitchStateAgree = 1,
  FLTCallSwitchStateReject = 2,
};

typedef NS_ENUM(NSUInteger, FLTCallTerminalCode) {
  FLTCallTerminalCodeNormal = 0,
  FLTCallTerminalCodeTokenError = 1,
  FLTCallTerminalCodeTimeOut = 2,
  FLTCallTerminalCodeBusy = 3,
  FLTCallTerminalCodeRtcInitError = 4,
  FLTCallTerminalCodeJoinRtcError = 5,
  FLTCallTerminalCodeCancelErrorParam = 6,
  FLTCallTerminalCodeCallFailed = 7,
  FLTCallTerminalCodeKicked = 8,
  FLTCallTerminalCodeEmptyUid = 9,
  FLTCallTerminalCodeRtcDisconnected = 10,
  FLTCallTerminalCodeCallerCancel = 11,
  FLTCallTerminalCodeCalleeCancel = 12,
  FLTCallTerminalCodeCalleeReject = 13,
  FLTCallTerminalCodeCallerRejected = 14,
  FLTCallTerminalCodeHangUp = 15,
  FLTCallTerminalCodeBeHangUp = 16,
  FLTCallTerminalCodeOtherRejected = 17,
  FLTCallTerminalCodeOtherAccepted = 18,
  FLTCallTerminalCodeUserRtcDisconnected = 19,
  FLTCallTerminalCodeUserRtcLeave = 20,
  FLTCallTerminalCodeAcceptFail = 21,
};

typedef NS_ENUM(NSUInteger, FLTNIMRtcCallStatus) {
  FLTNIMRtcCallStatusCompleted = 0,
  FLTNIMRtcCallStatusCancelled = 1,
  FLTNIMRtcCallStatusRejected = 2,
  FLTNIMRtcCallStatusTimeout = 3,
  FLTNIMRtcCallStatusBusy = 4,
};

typedef NS_ENUM(NSUInteger, FLTRtcVirtualBackgroundSourceStateReason) {
  FLTRtcVirtualBackgroundSourceStateReasonSuccess = 0,
  FLTRtcVirtualBackgroundSourceStateReasonFailure = 1,
  FLTRtcVirtualBackgroundSourceStateReasonNotSupported = 2,
};

@class FLTSimpleResponse;
@class FLTCallResponse;
@class FLTLCKConfig;
@class FLTSetupConfig;
@class FLTCallParam;
@class FLTCallPushConfig;
@class FLTUserInfo;
@class FLTSignalInfo;
@class FLTRtcInfo;
@class FLTCallInfo;
@class FLTHangupParam;
@class FLTSwitchParam;
@class FLTCallConfig;
@class FLTViewParam;
@class FLTInviteInfo;
@class FLTCallEndInfo;
@class FLTCallTypeChangeInfo;
@class FLTRecordConfig;
@class FLTNERtcASRCaptionConfig;
@class FLTNERtcAsrCaptionResult;
@class FLTNEGroupConfigParam;
@class FLTNEGroupPushParam;
@class FLTNEGroupCallParam;
@class FLTNEGroupAcceptParam;
@class FLTNEGroupHangupParam;
@class FLTNEGroupInviteParam;
@class FLTNEGroupJoinParam;
@class FLTNEGroupCallMember;
@class FLTNEGroupCallInfo;
@class FLTNEGroupCallEndEvent;
@class FLTNEGroupCallHangupEvent;
@class FLTNEAudioVolumeInfo;
@class FLTNEGroupViewParam;
@class FLTGroupSimpleResponse;
@class FLTGroupCallResponse;
@class FLTGroupAcceptResponse;
@class FLTGroupJoinResponse;
@class FLTGroupQueryCallInfoResponse;
@class FLTGroupQueryMembersResponse;

@interface FLTSimpleResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCode:(NSNumber *)code
    msg:(nullable NSString *)msg
    data1:(nullable NSNumber *)data1
    data2:(nullable NSNumber *)data2
    data3:(nullable NSString *)data3;
@property(nonatomic, strong) NSNumber * code;
@property(nonatomic, copy, nullable) NSString * msg;
@property(nonatomic, strong, nullable) NSNumber * data1;
@property(nonatomic, strong, nullable) NSNumber * data2;
@property(nonatomic, copy, nullable) NSString * data3;
@end

@interface FLTCallResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCode:(NSNumber *)code
    msg:(nullable NSString *)msg
    callInfo:(nullable FLTCallInfo *)callInfo;
@property(nonatomic, strong) NSNumber * code;
@property(nonatomic, copy, nullable) NSString * msg;
@property(nonatomic, strong, nullable) FLTCallInfo * callInfo;
@end

@interface FLTLCKConfig : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithEnableLiveCommunicationKit:(NSNumber *)enableLiveCommunicationKit
    ringtoneName:(nullable NSString *)ringtoneName;
@property(nonatomic, strong) NSNumber * enableLiveCommunicationKit;
@property(nonatomic, copy, nullable) NSString * ringtoneName;
@end

@interface FLTSetupConfig : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAppKey:(NSString *)appKey
    currentUserRtcUid:(nullable NSNumber *)currentUserRtcUid
    enableJoinRtcWhenCall:(nullable NSNumber *)enableJoinRtcWhenCall
    initRtcMode:(FLTCallInitRtcMode)initRtcMode
    lckConfig:(nullable FLTLCKConfig *)lckConfig;
@property(nonatomic, copy) NSString * appKey;
@property(nonatomic, strong, nullable) NSNumber * currentUserRtcUid;
@property(nonatomic, strong, nullable) NSNumber * enableJoinRtcWhenCall;
@property(nonatomic, assign) FLTCallInitRtcMode initRtcMode;
@property(nonatomic, strong, nullable) FLTLCKConfig * lckConfig;
@end

@interface FLTCallParam : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAccId:(NSString *)accId
    extraInfo:(nullable NSString *)extraInfo
    rtcChannelName:(nullable NSString *)rtcChannelName
    globalExtraCopy:(nullable NSString *)globalExtraCopy
    callType:(FLTCallType)callType
    pushConfig:(nullable FLTCallPushConfig *)pushConfig;
@property(nonatomic, copy) NSString * accId;
@property(nonatomic, copy, nullable) NSString * extraInfo;
@property(nonatomic, copy, nullable) NSString * rtcChannelName;
@property(nonatomic, copy, nullable) NSString * globalExtraCopy;
@property(nonatomic, assign) FLTCallType callType;
@property(nonatomic, strong, nullable) FLTCallPushConfig * pushConfig;
@end

@interface FLTCallPushConfig : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPushTitle:(nullable NSString *)pushTitle
    pushContent:(nullable NSString *)pushContent
    pushPayload:(nullable NSString *)pushPayload
    needBadge:(NSNumber *)needBadge
    needPush:(NSNumber *)needPush;
@property(nonatomic, copy, nullable) NSString * pushTitle;
@property(nonatomic, copy, nullable) NSString * pushContent;
@property(nonatomic, copy, nullable) NSString * pushPayload;
@property(nonatomic, strong) NSNumber * needBadge;
@property(nonatomic, strong) NSNumber * needPush;
@end

@interface FLTUserInfo : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAccId:(NSString *)accId
    uid:(NSNumber *)uid;
@property(nonatomic, copy) NSString * accId;
@property(nonatomic, strong) NSNumber * uid;
@end

@interface FLTSignalInfo : NSObject
+ (instancetype)makeWithChannelId:(nullable NSString *)channelId
    requestId:(nullable NSString *)requestId
    channelName:(nullable NSString *)channelName
    extraInfo:(nullable NSString *)extraInfo
    globalExtraCopy:(nullable NSString *)globalExtraCopy;
@property(nonatomic, copy, nullable) NSString * channelId;
@property(nonatomic, copy, nullable) NSString * requestId;
@property(nonatomic, copy, nullable) NSString * channelName;
@property(nonatomic, copy, nullable) NSString * extraInfo;
@property(nonatomic, copy, nullable) NSString * globalExtraCopy;
@end

@interface FLTRtcInfo : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithChannelName:(nullable NSString *)channelName
    token:(nullable NSString *)token
    uid:(NSNumber *)uid
    cid:(NSNumber *)cid;
@property(nonatomic, copy, nullable) NSString * channelName;
@property(nonatomic, copy, nullable) NSString * token;
@property(nonatomic, strong) NSNumber * uid;
@property(nonatomic, strong) NSNumber * cid;
@end

@interface FLTCallInfo : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCallId:(NSString *)callId
    currentAccId:(NSString *)currentAccId
    callerInfo:(nullable FLTUserInfo *)callerInfo
    calleeInfo:(nullable FLTUserInfo *)calleeInfo
    callType:(FLTCallType)callType
    signalInfo:(nullable FLTSignalInfo *)signalInfo
    rtcInfo:(nullable FLTRtcInfo *)rtcInfo
    callStatus:(FLTCallEngineStatus)callStatus;
@property(nonatomic, copy) NSString * callId;
@property(nonatomic, copy) NSString * currentAccId;
@property(nonatomic, strong, nullable) FLTUserInfo * callerInfo;
@property(nonatomic, strong, nullable) FLTUserInfo * calleeInfo;
@property(nonatomic, assign) FLTCallType callType;
@property(nonatomic, strong, nullable) FLTSignalInfo * signalInfo;
@property(nonatomic, strong, nullable) FLTRtcInfo * rtcInfo;
@property(nonatomic, assign) FLTCallEngineStatus callStatus;
@end

@interface FLTHangupParam : NSObject
+ (instancetype)makeWithChannelId:(nullable NSString *)channelId
    extraString:(nullable NSString *)extraString;
@property(nonatomic, copy, nullable) NSString * channelId;
@property(nonatomic, copy, nullable) NSString * extraString;
@end

@interface FLTSwitchParam : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCallType:(FLTCallType)callType
    state:(FLTCallSwitchState)state;
@property(nonatomic, assign) FLTCallType callType;
@property(nonatomic, assign) FLTCallSwitchState state;
@end

@interface FLTCallConfig : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithEnableOffline:(NSNumber *)enableOffline
    enableSwitchVideoConfirm:(NSNumber *)enableSwitchVideoConfirm
    enableSwitchAudioConfirm:(NSNumber *)enableSwitchAudioConfirm;
@property(nonatomic, strong) NSNumber * enableOffline;
@property(nonatomic, strong) NSNumber * enableSwitchVideoConfirm;
@property(nonatomic, strong) NSNumber * enableSwitchAudioConfirm;
@end

@interface FLTViewParam : NSObject
+ (instancetype)makeWithViewId:(nullable NSNumber *)viewId;
@property(nonatomic, strong, nullable) NSNumber * viewId;
@end

@interface FLTInviteInfo : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCallerAccId:(NSString *)callerAccId
    callType:(FLTCallType)callType
    extraInfo:(nullable NSString *)extraInfo
    channelId:(nullable NSString *)channelId;
@property(nonatomic, copy) NSString * callerAccId;
@property(nonatomic, assign) FLTCallType callType;
@property(nonatomic, copy, nullable) NSString * extraInfo;
@property(nonatomic, copy, nullable) NSString * channelId;
@end

@interface FLTCallEndInfo : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithReasonCode:(FLTCallTerminalCode)reasonCode
    extraString:(nullable NSString *)extraString
    message:(nullable NSString *)message;
@property(nonatomic, assign) FLTCallTerminalCode reasonCode;
@property(nonatomic, copy, nullable) NSString * extraString;
@property(nonatomic, copy, nullable) NSString * message;
@end

@interface FLTCallTypeChangeInfo : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCallType:(FLTCallType)callType
    state:(FLTCallSwitchState)state;
@property(nonatomic, assign) FLTCallType callType;
@property(nonatomic, assign) FLTCallSwitchState state;
@end

@interface FLTRecordConfig : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAccId:(NSString *)accId
    callType:(FLTCallType)callType
    callState:(FLTNIMRtcCallStatus)callState;
@property(nonatomic, copy) NSString * accId;
@property(nonatomic, assign) FLTCallType callType;
@property(nonatomic, assign) FLTNIMRtcCallStatus callState;
@end

@interface FLTNERtcASRCaptionConfig : NSObject
+ (instancetype)makeWithSrcLanguage:(nullable NSString *)srcLanguage
    srcLanguages:(nullable NSArray<NSString *> *)srcLanguages
    dstLanguage:(nullable NSString *)dstLanguage
    dstLanguages:(nullable NSArray<NSString *> *)dstLanguages
    needTranslateSameLanguage:(nullable NSNumber *)needTranslateSameLanguage;
/// 指定字幕的源语言。默认为AUTO
@property(nonatomic, copy, nullable) NSString * srcLanguage;
/// 指定字幕的多个源语言。默认为空
@property(nonatomic, strong, nullable) NSArray<NSString *> * srcLanguages;
/// 指定字幕的目标语言（已废弃，建议使用 dstLanguages）
@property(nonatomic, copy, nullable) NSString * dstLanguage;
/// 指定字幕的目标语言
@property(nonatomic, strong, nullable) NSArray<NSString *> * dstLanguages;
/// 当源语言与设置的目标语言相同时，是否仍要翻译。默认为 false
@property(nonatomic, strong, nullable) NSNumber * needTranslateSameLanguage;
@end

@interface FLTNERtcAsrCaptionResult : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithUid:(NSNumber *)uid
    isLocalUser:(NSNumber *)isLocalUser
    timestamp:(NSNumber *)timestamp
    content:(nullable NSString *)content
    language:(nullable NSString *)language
    haveTranslation:(NSNumber *)haveTranslation
    translatedText:(nullable NSString *)translatedText
    translationLanguage:(nullable NSString *)translationLanguage
    isFinal:(NSNumber *)isFinal;
@property(nonatomic, strong) NSNumber * uid;
@property(nonatomic, strong) NSNumber * isLocalUser;
@property(nonatomic, strong) NSNumber * timestamp;
@property(nonatomic, copy, nullable) NSString * content;
@property(nonatomic, copy, nullable) NSString * language;
@property(nonatomic, strong) NSNumber * haveTranslation;
@property(nonatomic, copy, nullable) NSString * translatedText;
@property(nonatomic, copy, nullable) NSString * translationLanguage;
@property(nonatomic, strong) NSNumber * isFinal;
@end

/// 群呼引擎配置参数
@interface FLTNEGroupConfigParam : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAppKey:(NSString *)appKey
    rtcSafeMode:(nullable NSNumber *)rtcSafeMode
    timeout:(nullable NSNumber *)timeout
    currentUserRtcUid:(nullable NSNumber *)currentUserRtcUid;
@property(nonatomic, copy) NSString * appKey;
/// RTC 安全模式：0=调试模式，1=安全模式
@property(nonatomic, strong, nullable) NSNumber * rtcSafeMode;
@property(nonatomic, strong, nullable) NSNumber * timeout;
@property(nonatomic, strong, nullable) NSNumber * currentUserRtcUid;
@end

/// 推送配置参数
@interface FLTNEGroupPushParam : NSObject
+ (instancetype)makeWithPushContent:(nullable NSString *)pushContent
    pushPayload:(nullable NSString *)pushPayload
    pushMode:(nullable NSNumber *)pushMode
    sound:(nullable NSString *)sound;
@property(nonatomic, copy, nullable) NSString * pushContent;
@property(nonatomic, copy, nullable) NSString * pushPayload;
@property(nonatomic, strong, nullable) NSNumber * pushMode;
@property(nonatomic, copy, nullable) NSString * sound;
@end

/// 发起群呼参数
@interface FLTNEGroupCallParam : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCallId:(nullable NSString *)callId
    calleeList:(NSArray<NSString *> *)calleeList
    groupId:(nullable NSString *)groupId
    groupType:(NSNumber *)groupType
    inviteMode:(nullable NSNumber *)inviteMode
    joinMode:(nullable NSNumber *)joinMode
    extraInfo:(nullable NSString *)extraInfo
    pushParam:(nullable FLTNEGroupPushParam *)pushParam;
@property(nonatomic, copy, nullable) NSString * callId;
@property(nonatomic, strong) NSArray<NSString *> * calleeList;
@property(nonatomic, copy, nullable) NSString * groupId;
@property(nonatomic, strong) NSNumber * groupType;
@property(nonatomic, strong, nullable) NSNumber * inviteMode;
@property(nonatomic, strong, nullable) NSNumber * joinMode;
@property(nonatomic, copy, nullable) NSString * extraInfo;
@property(nonatomic, strong, nullable) FLTNEGroupPushParam * pushParam;
@end

/// 接听群呼参数
@interface FLTNEGroupAcceptParam : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCallId:(NSString *)callId;
@property(nonatomic, copy) NSString * callId;
@end

/// 挂断群呼参数
@interface FLTNEGroupHangupParam : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCallId:(NSString *)callId
    reason:(nullable NSString *)reason;
@property(nonatomic, copy) NSString * callId;
@property(nonatomic, copy, nullable) NSString * reason;
@end

/// 邀请成员参数
@interface FLTNEGroupInviteParam : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCallId:(NSString *)callId
    calleeList:(NSArray<NSString *> *)calleeList;
@property(nonatomic, copy) NSString * callId;
@property(nonatomic, strong) NSArray<NSString *> * calleeList;
@end

/// 主动加入参数
@interface FLTNEGroupJoinParam : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCallId:(NSString *)callId;
@property(nonatomic, copy) NSString * callId;
@end

/// 群呼成员信息
@interface FLTNEGroupCallMember : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAccId:(NSString *)accId
    rtcUid:(nullable NSNumber *)rtcUid
    state:(nullable NSNumber *)state
    action:(nullable NSString *)action
    reason:(nullable NSString *)reason;
@property(nonatomic, copy) NSString * accId;
@property(nonatomic, strong, nullable) NSNumber * rtcUid;
@property(nonatomic, strong, nullable) NSNumber * state;
@property(nonatomic, copy, nullable) NSString * action;
@property(nonatomic, copy, nullable) NSString * reason;
@end

/// 群呼信息
@interface FLTNEGroupCallInfo : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCallId:(NSString *)callId
    groupId:(nullable NSString *)groupId
    groupType:(nullable NSNumber *)groupType
    callerAccId:(nullable NSString *)callerAccId
    callerRtcUid:(nullable NSNumber *)callerRtcUid
    memberList:(nullable NSArray<FLTNEGroupCallMember *> *)memberList
    inviteMode:(nullable NSNumber *)inviteMode
    joinMode:(nullable NSNumber *)joinMode
    extraInfo:(nullable NSString *)extraInfo
    startTimestamp:(nullable NSNumber *)startTimestamp;
@property(nonatomic, copy) NSString * callId;
@property(nonatomic, copy, nullable) NSString * groupId;
@property(nonatomic, strong, nullable) NSNumber * groupType;
@property(nonatomic, copy, nullable) NSString * callerAccId;
@property(nonatomic, strong, nullable) NSNumber * callerRtcUid;
@property(nonatomic, strong, nullable) NSArray<FLTNEGroupCallMember *> * memberList;
@property(nonatomic, strong, nullable) NSNumber * inviteMode;
@property(nonatomic, strong, nullable) NSNumber * joinMode;
@property(nonatomic, copy, nullable) NSString * extraInfo;
@property(nonatomic, strong, nullable) NSNumber * startTimestamp;
@end

/// 群呼结束事件
@interface FLTNEGroupCallEndEvent : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCallId:(NSString *)callId
    reason:(NSNumber *)reason
    message:(nullable NSString *)message;
@property(nonatomic, copy) NSString * callId;
@property(nonatomic, strong) NSNumber * reason;
@property(nonatomic, copy, nullable) NSString * message;
@end

/// 成员挂断事件
@interface FLTNEGroupCallHangupEvent : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCallId:(NSString *)callId
    reason:(NSNumber *)reason
    message:(nullable NSString *)message;
@property(nonatomic, copy) NSString * callId;
@property(nonatomic, strong) NSNumber * reason;
@property(nonatomic, copy, nullable) NSString * message;
@end

/// 音量信息
@interface FLTNEAudioVolumeInfo : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithUid:(NSNumber *)uid
    volume:(NSNumber *)volume;
@property(nonatomic, strong) NSNumber * uid;
@property(nonatomic, strong) NSNumber * volume;
@end

/// 群呼视图设置参数
@interface FLTNEGroupViewParam : NSObject
+ (instancetype)makeWithViewId:(nullable NSNumber *)viewId
    uid:(nullable NSNumber *)uid;
@property(nonatomic, strong, nullable) NSNumber * viewId;
@property(nonatomic, strong, nullable) NSNumber * uid;
@end

/// 群呼简单响应
@interface FLTGroupSimpleResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCode:(NSNumber *)code
    msg:(nullable NSString *)msg;
@property(nonatomic, strong) NSNumber * code;
@property(nonatomic, copy, nullable) NSString * msg;
@end

/// 发起群呼响应
@interface FLTGroupCallResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCode:(NSNumber *)code
    msg:(nullable NSString *)msg
    callInfo:(nullable FLTNEGroupCallInfo *)callInfo;
@property(nonatomic, strong) NSNumber * code;
@property(nonatomic, copy, nullable) NSString * msg;
@property(nonatomic, strong, nullable) FLTNEGroupCallInfo * callInfo;
@end

/// 接听群呼响应
@interface FLTGroupAcceptResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCode:(NSNumber *)code
    msg:(nullable NSString *)msg
    callInfo:(nullable FLTNEGroupCallInfo *)callInfo;
@property(nonatomic, strong) NSNumber * code;
@property(nonatomic, copy, nullable) NSString * msg;
@property(nonatomic, strong, nullable) FLTNEGroupCallInfo * callInfo;
@end

/// 加入群呼响应
@interface FLTGroupJoinResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCode:(NSNumber *)code
    msg:(nullable NSString *)msg
    callInfo:(nullable FLTNEGroupCallInfo *)callInfo;
@property(nonatomic, strong) NSNumber * code;
@property(nonatomic, copy, nullable) NSString * msg;
@property(nonatomic, strong, nullable) FLTNEGroupCallInfo * callInfo;
@end

/// 查询群呼信息响应
@interface FLTGroupQueryCallInfoResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCode:(NSNumber *)code
    msg:(nullable NSString *)msg
    callInfo:(nullable FLTNEGroupCallInfo *)callInfo;
@property(nonatomic, strong) NSNumber * code;
@property(nonatomic, copy, nullable) NSString * msg;
@property(nonatomic, strong, nullable) FLTNEGroupCallInfo * callInfo;
@end

/// 查询成员列表响应
@interface FLTGroupQueryMembersResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCode:(NSNumber *)code
    msg:(nullable NSString *)msg
    members:(nullable NSArray<FLTNEGroupCallMember *> *)members;
@property(nonatomic, strong) NSNumber * code;
@property(nonatomic, copy, nullable) NSString * msg;
@property(nonatomic, strong, nullable) NSArray<FLTNEGroupCallMember *> * members;
@end

/// The codec used by FLTCallKitApi.
NSObject<FlutterMessageCodec> *FLTCallKitApiGetCodec(void);

@protocol FLTCallKitApi
- (void)setupConfig:(FLTSetupConfig *)config completion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getVersionWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)callParam:(FLTCallParam *)param completion:(void (^)(FLTCallResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)acceptWithCompletion:(void (^)(FLTCallResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)hangupParam:(FLTHangupParam *)param completion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)switchCallTypeParam:(FLTSwitchParam *)param completion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)setTimeoutTime:(NSNumber *)time completion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)setupLocalViewParam:(FLTViewParam *)param completion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)setupRemoteViewParam:(FLTViewParam *)param completion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)enableLocalVideoEnable:(NSNumber *)enable completion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)muteLocalVideoMuted:(NSNumber *)muted completion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)muteLocalAudioMuted:(NSNumber *)muted completion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)switchCameraWithCompletion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)isSpeakerphoneOnWithCompletion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)setSpeakerphoneOnEnable:(NSNumber *)enable completion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)setCallConfigConfig:(FLTCallConfig *)config completion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)getCallInfoWithCompletion:(void (^)(FLTCallInfo *_Nullable, FlutterError *_Nullable))completion;
- (void)getCallConfigWithCompletion:(void (^)(FLTCallConfig *_Nullable, FlutterError *_Nullable))completion;
- (void)destroyWithCompletion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)startASRCaptionConfig:(FLTNERtcASRCaptionConfig *)config completion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)stopASRCaptionWithCompletion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)getUserWithRtcUidUid:(NSNumber *)uid completion:(void (^)(FLTUserInfo *_Nullable, FlutterError *_Nullable))completion;
- (void)setCallRecordProviderEnable:(NSNumber *)enable completion:(void (^)(FLTSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
@end

extern void FLTCallKitApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTCallKitApi> *_Nullable api);

/// The codec used by FLTCallKitEventSink.
NSObject<FlutterMessageCodec> *FLTCallKitEventSinkGetCodec(void);

@interface FLTCallKitEventSink : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onReceiveInvitedInfo:(FLTInviteInfo *)info completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onCallEndInfo:(FLTCallEndInfo *)info completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onCallConnectedInfo:(FLTCallInfo *)info completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onLCKAcceptResponse:(FLTCallResponse *)response completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onLCKHangupResponse:(FLTSimpleResponse *)response completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onCallTypeChangeInfo:(FLTCallTypeChangeInfo *)info completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onVideoAvailableAvailable:(NSNumber *)available userID:(NSString *)userID completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onVideoMutedMuted:(NSNumber *)muted userID:(NSString *)userID completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onAudioMutedMuted:(NSNumber *)muted userID:(NSString *)userID completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onLocalAudioMutedMuted:(NSNumber *)muted completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onRtcInitEndWithCompletion:(void (^)(FlutterError *_Nullable))completion;
- (void)onRecordSendConfig:(FLTRecordConfig *)config completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onNERtcEngineVirtualBackgroundSourceEnabledEnabled:(NSNumber *)enabled reason:(NSNumber *)reason completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onAsrCaptionStateChangedAsrState:(NSNumber *)asrState code:(NSNumber *)code message:(NSString *)message completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onAsrCaptionResultResult:(NSArray<FLTNERtcAsrCaptionResult *> *)result completion:(void (^)(FlutterError *_Nullable))completion;
@end

/// The codec used by FLTGroupCallKitApi.
NSObject<FlutterMessageCodec> *FLTGroupCallKitApiGetCodec(void);

@protocol FLTGroupCallKitApi
/// 初始化群呼引擎
- (void)initConfig:(FLTNEGroupConfigParam *)config completion:(void (^)(FLTGroupSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
/// 释放群呼引擎
- (void)releaseWithCompletion:(void (^)(FLTGroupSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
/// 发起群呼
- (void)groupCallParam:(FLTNEGroupCallParam *)param completion:(void (^)(FLTGroupCallResponse *_Nullable, FlutterError *_Nullable))completion;
/// 接听群呼
- (void)groupAcceptParam:(FLTNEGroupAcceptParam *)param completion:(void (^)(FLTGroupAcceptResponse *_Nullable, FlutterError *_Nullable))completion;
/// 挂断/拒绝群呼
- (void)groupHangupParam:(FLTNEGroupHangupParam *)param completion:(void (^)(FLTGroupSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
/// 邀请新成员
- (void)groupInviteParam:(FLTNEGroupInviteParam *)param completion:(void (^)(FLTGroupSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
/// 主动加入群呼
- (void)groupJoinParam:(FLTNEGroupJoinParam *)param completion:(void (^)(FLTGroupJoinResponse *_Nullable, FlutterError *_Nullable))completion;
/// 查询群呼信息
- (void)groupQueryCallInfoCallId:(NSString *)callId completion:(void (^)(FLTGroupQueryCallInfoResponse *_Nullable, FlutterError *_Nullable))completion;
/// 查询成员列表
- (void)groupQueryMembersCallId:(NSString *)callId completion:(void (^)(FLTGroupQueryMembersResponse *_Nullable, FlutterError *_Nullable))completion;
/// 开关本端视频采集
- (void)enableLocalVideoEnable:(NSNumber *)enable completion:(void (^)(FLTGroupSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
/// 静音本端视频发送
- (void)muteLocalVideoMute:(NSNumber *)mute completion:(void (^)(FLTGroupSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
/// 开关本端音频采集和发送
- (void)enableLocalAudioEnable:(NSNumber *)enable completion:(void (^)(FLTGroupSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
/// 静音本端音频发送
- (void)muteLocalAudioMute:(NSNumber *)mute completion:(void (^)(FLTGroupSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
/// 设置扬声器开关
- (void)setSpeakerphoneOnEnable:(NSNumber *)enable completion:(void (^)(FLTGroupSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
/// 获取扬声器状态
- (void)isSpeakerphoneOnWithCompletion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
/// 切换前后摄像头
- (void)switchCameraWithCompletion:(void (^)(FLTGroupSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
/// 设置本端视频画布
- (void)setupLocalViewParam:(FLTNEGroupViewParam *)param completion:(void (^)(FLTGroupSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
/// 设置远端成员视频画布
- (void)setupRemoteViewParam:(FLTNEGroupViewParam *)param completion:(void (^)(FLTGroupSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
/// 开启/关闭音量回调
- (void)enableAudioVolumeIndicationEnable:(NSNumber *)enable interval:(NSNumber *)interval completion:(void (^)(FLTGroupSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
/// 设置音视频通话参数
- (void)setParametersParams:(NSDictionary<NSString *, id> *)params completion:(void (^)(FLTGroupSimpleResponse *_Nullable, FlutterError *_Nullable))completion;
@end

extern void FLTGroupCallKitApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTGroupCallKitApi> *_Nullable api);

/// The codec used by FLTGroupCallKitEventSink.
NSObject<FlutterMessageCodec> *FLTGroupCallKitEventSinkGetCodec(void);

/// 群呼业务回调
@interface FLTGroupCallKitEventSink : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
/// 收到群呼邀请
- (void)onReceiveGroupInvitationInfo:(FLTNEGroupCallInfo *)info completion:(void (^)(FlutterError *_Nullable))completion;
/// 成员列表变更
- (void)onGroupMemberListChangedCallId:(NSString *)callId members:(NSArray<FLTNEGroupCallMember *> *)members completion:(void (^)(FlutterError *_Nullable))completion;
/// 成员挂断回调
- (void)onGroupCallHangupEvent:(FLTNEGroupCallHangupEvent *)event completion:(void (^)(FlutterError *_Nullable))completion;
/// 群呼结束回调
- (void)onGroupCallEndEvent:(FLTNEGroupCallEndEvent *)event completion:(void (^)(FlutterError *_Nullable))completion;
@end

/// The codec used by FLTGroupMediaEventSink.
NSObject<FlutterMessageCodec> *FLTGroupMediaEventSinkGetCodec(void);

/// 媒体事件回调
@interface FLTGroupMediaEventSink : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
/// 远端用户开启音频
- (void)onUserAudioStartUid:(NSNumber *)uid completion:(void (^)(FlutterError *_Nullable))completion;
/// 远端用户关闭音频
- (void)onUserAudioStopUid:(NSNumber *)uid completion:(void (^)(FlutterError *_Nullable))completion;
/// 远端用户音频静音状态变更
- (void)onUserAudioMuteUid:(NSNumber *)uid muted:(NSNumber *)muted completion:(void (^)(FlutterError *_Nullable))completion;
/// 远端用户开启视频
- (void)onUserVideoStartUid:(NSNumber *)uid maxProfile:(NSNumber *)maxProfile completion:(void (^)(FlutterError *_Nullable))completion;
/// 远端用户关闭视频
- (void)onUserVideoStopUid:(NSNumber *)uid completion:(void (^)(FlutterError *_Nullable))completion;
/// 远端用户视频静音状态变更
- (void)onUserVideoMuteUid:(NSNumber *)uid muted:(NSNumber *)muted completion:(void (^)(FlutterError *_Nullable))completion;
/// 远端用户音量回调
- (void)onRemoteAudioVolumeIndicationVolumes:(NSArray<FLTNEAudioVolumeInfo *> *)volumes totalVolume:(NSNumber *)totalVolume completion:(void (^)(FlutterError *_Nullable))completion;
/// 与服务器连接中断
- (void)onDisconnectReason:(NSNumber *)reason completion:(void (^)(FlutterError *_Nullable))completion;
/// 音视频组件运行时错误
- (void)onErrorCode:(NSNumber *)code completion:(void (^)(FlutterError *_Nullable))completion;
@end

/// The codec used by FLTCallkitVideoRendererApi.
NSObject<FlutterMessageCodec> *FLTCallkitVideoRendererApiGetCodec(void);

@protocol FLTCallkitVideoRendererApi
/// 创建视频渲染器，返回 textureId
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)createVideoRendererWithError:(FlutterError *_Nullable *_Nonnull)error;
/// 设置镜像
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)setMirrorTextureId:(NSNumber *)textureId mirror:(NSNumber *)mirror error:(FlutterError *_Nullable *_Nonnull)error;
/// 绑定为本地视频画布
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)setupLocalVideoRendererTextureId:(NSNumber *)textureId error:(FlutterError *_Nullable *_Nonnull)error;
/// 绑定为远端视频画布
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)setupRemoteVideoRendererUid:(NSNumber *)uid textureId:(NSNumber *)textureId error:(FlutterError *_Nullable *_Nonnull)error;
/// 释放视频渲染器
- (void)disposeVideoRendererTextureId:(NSNumber *)textureId error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTCallkitVideoRendererApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTCallkitVideoRendererApi> *_Nullable api);

NS_ASSUME_NONNULL_END
